### ISSUE TITLE
Missing Geometry: Cameroon

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#134]
The Missing Geometry query indicates that DATIM contains eight health districts that lack geometry. This ticket tracks the effort to improve the completeness of Cameroon's map at Level 5.

**Comment by NateHeard** [comment]
Of the unmatched units at the health district level, Bamenda 3 and Belabo are arrondissements and do not seem to be districts. Dang, Kumba-South, Mozogo, Mvog-Ada, and Odza were not located on commonly available maps. Some seem to be towns or other populated places rather than districts. The current health district shapefile has 199 polygons and each one has a uid assigned to it.
