### ISSUE TITLE
Coordinate completeness & quality report

### ISSUE THREAD

**Issue by gsarfaty** [ICPI/GIS#32]
Need to package coordinate checks into useful outputs.

**Comment by NateHeard** [comment]
This is a fabulous draft. I think we might frame anomaly two a little more strongly. "Truncated coordinates" could be phrased as lack of precision. "Lacks precision"? I need to learn how to make a floaty filter button. How did you decide what's "hot"? It's challenging because these errors aren't on a straightforward continuum. No coordinates and beyond 2km are almost equivalent but almost worse.

**Comment by NateHeard** [comment]
The only other useful filter I can think of is prioritization. In an OU like Bots, country teams likely memorize district prioritization. It would be a more useful filter for OUs with many more PSNUs.

**Comment by gsarfaty** [comment]
Draft is in the [Spatial Data Mgmt folder>November ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FClusters%2FGeospatial%20Data%2FProjects%2FSpatial%20Data%20Management%2FNovember%20Facility%20Coordinate%20Audit&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D)

**Comment by gsarfaty** [comment]
Reports packaged and sent by @NateHeard
