### ISSUE TITLE
Panorama Development Next Steps 

### ISSUE THREAD

**Issue by gsarfaty** [ICPI/GIS#87]
- [x] meeting w JH re: involvement in Pano Dev earlier on in process; more intergration of gis cluster as cross-cutting instead of standalone [@CmdrKerfy ]
- [x] Assign @CmdrKerfy, @NateHeard, @gsarfaty to technical clusters for new dossier development outreach

- HIV Prevention

- HIV/TB Diagnosis @CmdrKerfy

- HSS & KP

Assign @CmdrKerfy, @NateHeard, @gsarfaty to technical clusters for enhancement requests for existing dossiers

- Testing @NateHeard

- Treatment @NateHeard

- Viral load @NateHeard

- [x] create technical questions on limitations of VC [all]
- can VC display symbology based on polygon centroids 

- turn on and off layers

- change basemap as needed

- ability to have psnu labels

**Comment by CmdrKerfy** [comment]
I'm working on compiling known technical issues we've received based on testing and limited user feedback. Please let me know if you've come across any others so that we can group together into one document for handover.

**Known Issues:**
- No labels for PSNUs
- No visualization of PSNUs that do not have DATIM information
- No method for the user to change base layers
- No method for the user to turn off/on health facilities

**To Be Created or Added:**
- Finalize and send our style guide to the DS team so that our formatting will be preserved post-publication
- Investigate whether or not VC can convert the existing geodata into centerpoints. If not, we can quickly convert the dataset handed off to the Pano team into point data.

**Comment by NateHeard** [comment]
We have a set of enhancements and bugs to work on this cycle. This information will be added to the Planned Dossier Updates Template and submitted to the DIV co-leads by COB Monday 5/18. @NateHeard will circulate the template to @gsarfaty and @CmdrKerfy on Monday morning for review and sign off by COB.

**Enhancements**

- HIV/TB chapter as outlined in https://github.com/ICPI/GIS/issues/88
- Add text to existing map pages that guides users on how to navigate maps, particularly with regard to indicator navigation using the interactive legend.
- Add PSNU label function to existing maps (if possible to turn on and off)
- Add boundaries for PSNUs that do not have data
- Remove green choropleth ramp due to conflict with OSM basemap
- Identify whether it's possible to change base layers in PROD
- Identify whether it's possible to turn health facilities on/off in PROD

**Bugs**

- Legend persistence

**Comment by NateHeard** [comment]
- June 22: Development starts
- July 22: Add real data to mock data
- July 24: Data Strong Code Review
- July 28-29: QC of Dossiers, Round 1
- July 31: Pano Content Development Ends 
- August 17-19:  QC of Dossiers, Round 2

**Comment by NateHeard** [comment]
This cycle has closed. Strategic outreach to other clusters early in next development cycle should start early.
